force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Product__c/Service_Product__c.object-meta.xml
<CustomObject>
    <label>Service Product</label>
    <nameField>
        <label>Service Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Product__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legal_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Currency_Type__c.field-meta.xml
<CustomField>
    <fullName>Currency_Type__c</fullName>
    <label>Currency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Is_Free__c.field-meta.xml
<CustomField>
    <fullName>Is_Free__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Products</relationshipLabel>
    <relationshipName>Service_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Products</relationshipLabel>
    <relationshipName>Service_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Legal_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Legal Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductSummaryController.cls
public with sharing class ProductSummaryController {
    
    /**
     * @description  make query to get case record
     * @author       Mikel Nieto 
     * @date         Dec, 2022
     * @param        Id caseId
     * @return       Case caseAct
     **/
    @AuraEnabled(cacheable=true)
    public static Case getCase(Id caseId){
        Case caseAct;
        List<Case> caseList = [SELECT Id, ContactId, Contact.Product__c,
                        Contact.Product__r.name, Contact.Home_Country__c                       
                       FROM Case
                       WHERE Id =:caseId];

        if(!caseList.isEmpty())
        {
            caseAct = caseList.get(0);
        }

        return caseAct;
    }

    /**
     * @description  make query to get Service Products records
     * @author       Mikel Nieto 
     * @date         Apr, 2022
     * @param        Case c
     * @return       List<Service_Charge__c>  serviceProducts
     **/
    @AuraEnabled
    public static List<Service_Product__c> getServiceProducts(Case c){
        List<Service_Product__c> serviceProducts = new List<Service_Product__c>();
        if(c != null && c.ContactId != null &&  c.Contact.Home_Country__c != null && c.Contact.Product__c != null){
            serviceProducts = [SELECT Id, Price__c, Country_Code__c, Is_Free__c, Currency_Type__c,
                                Service__c, Service__r.Name, Product__c, Product__r.Name
                                FROM Service_Product__c
                                WHERE Product__c =: c.Contact.Product__c
                                AND Product__r.IsActive = true
                                AND Country_Code__c =: c.Contact.Home_Country__c];
        }
        return serviceProducts;
    }

}