force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Product__c/Service_Product__c.object-meta.xml
<CustomObject>
    <label>Service Product</label>
    <nameField>
        <label>Service Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Product__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Legal_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Currency_Type__c.field-meta.xml
<CustomField>
    <fullName>Currency_Type__c</fullName>
    <label>Currency Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Is_Free__c.field-meta.xml
<CustomField>
    <fullName>Is_Free__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Products</relationshipLabel>
    <relationshipName>Service_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Product__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Products</relationshipLabel>
    <relationshipName>Service_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Legal_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Legal Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductSummaryController_Test.cls
@isTest
public class ProductSummaryController_Test {
    @testSetup
    public static void setUp()
    {
        Product2 p = new Product2(Name = 'Metal', IsActive = true);
        insert p;

        List<Service__c> servList = new List<Service__c>();
        Service__c s1 =new Service__c(Name = 'Cost per Calendar Month');
        servList.add(s1);
        Service__c s2 =new Service__c(Name = 'Card Replacement Cost');
        servList.add(s2);        
        
        insert servList;
        List<Service_Product__c> splist = new List<Service_Product__c>();
            
        Service_Product__c sp1 = new Service_Product__c(
                Product__c = p.Id,
                Service__c = s1.Id,
                Price__c = 106.87,
                Is_Free__c = false,
                Currency_Type__c = 'EUR',
                Country_Code__c = 'ES');

        splist.add(sp1);
        Service_Product__c sp2 = new Service_Product__c(
            Product__c = p.Id,
            Service__c = s2.Id,
            Is_Free__c = true,
            Currency_Type__c = 'EUR',
            Country_Code__c = 'ES');
        
        splist.add(sp2);
        insert splist; 
            
        Contact  c = new Contact(FirstName = 'Test',
                                LastName = 'User',
                                 Product__c = p.Id,
                                Home_Country__c = 'ES',
                                email = 'test@gmail.com' );
        insert c;
        
        Case cs = new Case(Subject = 'caseTest',
                          ContactId = c.Id,
                          Status = 'New',
                          Origin = 'Email');
        insert cs;
        
    }
    
    @isTest
    public static void getServiceProductsTest(){
        Id caseId = [Select Id from Case where Status ='New'].Id;        
        Test.startTest();
        Case c = ProductSummaryController.getCase(caseId);
        List<Service_Product__c> serviceProd = ProductSummaryController.getServiceProducts(c);
        Test.stopTest();
        System.assertEquals(serviceProd.size(), 2);
    }
    
}